# [dbo].[DetalleVenta]

In [0]:
USE [TiendaDeCompras]
GO

In [0]:
/****** Object:  Table [dbo].[DetalleVenta]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DetalleVenta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodigoVenta] [int] NOT NULL,
	[CodigoProducto] [int] NOT NULL,
	[CantidadDetalleVenta] [int] NOT NULL,
	[PrecioDetalleVenta] [decimal](11, 2) NOT NULL,
	[SubtotalDetalleVenta] [decimal](11, 2) NOT NULL,
 CONSTRAINT [PK_DetalleVenta] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Producto]

In [0]:
/****** Object:  Table [dbo].[Producto]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreProducto] [varchar](100) NOT NULL,
	[DescripcionProducto] [varchar](100) NOT NULL,
	[PrecioProducto] [decimal](11, 2) NOT NULL,
	[ImagenProducto] [varchar](500) NOT NULL,
	[CantidadProducto] [int] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Roles]

In [0]:
/****** Object:  Table [dbo].[Roles]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Rol] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[UsuarioLogin]

In [0]:
/****** Object:  Table [dbo].[UsuarioLogin]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsuarioLogin](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmailLogin] [varchar](100) NOT NULL,
	[Password] [varchar](20) NOT NULL,
	[CodigoRol] [int] NOT NULL,
 CONSTRAINT [PK_UsuarioLogin] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Venta]

In [0]:
/****** Object:  Table [dbo].[Venta]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Venta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClienteVenta] [varchar](100) NOT NULL,
	[FechaVenta] [datetime] NOT NULL,
	[SubtotalVenta] [decimal](11, 2) NOT NULL,
	[IvaVenta] [decimal](11, 2) NOT NULL,
	[TotalVenta] [decimal](12, 2) NOT NULL,
 CONSTRAINT [PK_Venta] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DetalleVenta]

In [0]:
SET IDENTITY_INSERT [dbo].[DetalleVenta] ON 
INSERT [dbo].[DetalleVenta] ([Id], [CodigoVenta], [CodigoProducto], [CantidadDetalleVenta], [PrecioDetalleVenta], [SubtotalDetalleVenta]) VALUES (1, 1, 1, 1, CAST(2000000.00 AS Decimal(11, 2)), CAST(2000000.00 AS Decimal(11, 2)))
INSERT [dbo].[DetalleVenta] ([Id], [CodigoVenta], [CodigoProducto], [CantidadDetalleVenta], [PrecioDetalleVenta], [SubtotalDetalleVenta]) VALUES (2, 2, 2, 2, CAST(1750000.00 AS Decimal(11, 2)), CAST(3500000.00 AS Decimal(11, 2)))
INSERT [dbo].[DetalleVenta] ([Id], [CodigoVenta], [CodigoProducto], [CantidadDetalleVenta], [PrecioDetalleVenta], [SubtotalDetalleVenta]) VALUES (3, 3, 3, 5, CAST(4000000.00 AS Decimal(11, 2)), CAST(20000000.00 AS Decimal(11, 2)))
SET IDENTITY_INSERT [dbo].[DetalleVenta] OFF
GO

# [dbo].[Producto]

In [0]:
SET IDENTITY_INSERT [dbo].[Producto] ON 
INSERT [dbo].[Producto] ([Id], [NombreProducto], [DescripcionProducto], [PrecioProducto], [ImagenProducto], [CantidadProducto]) VALUES (1, N'SONY VAIO', N'PC PORTATIL', CAST(2000000.00 AS Decimal(11, 2)), N'C:\Users\WIN10 PRO\source\repos\Carvajal\BlazorServerAppTiendaCompras\PcPortatilSonyVaio1.jpg', 20)
INSERT [dbo].[Producto] ([Id], [NombreProducto], [DescripcionProducto], [PrecioProducto], [ImagenProducto], [CantidadProducto]) VALUES (2, N'LENOVO', N'PC PORTATIL', CAST(1750000.00 AS Decimal(11, 2)), N'C:\Users\WIN10 PRO\source\repos\Carvajal\BlazorServerAppTiendaCompras\PcPortatilLenovo.jpg', 10)
INSERT [dbo].[Producto] ([Id], [NombreProducto], [DescripcionProducto], [PrecioProducto], [ImagenProducto], [CantidadProducto]) VALUES (3, N'APPLE', N'PC PORTATIL MC BOOK', CAST(4000000.00 AS Decimal(11, 2)), N'C:\Users\WIN10 PRO\source\repos\Carvajal\BlazorServerAppTiendaCompras\PcPortatilAppleMacBook.jpg', 15)
SET IDENTITY_INSERT [dbo].[Producto] OFF
GO

# [dbo].[Roles]

In [0]:
SET IDENTITY_INSERT [dbo].[Roles] ON 
INSERT [dbo].[Roles] ([Id], [Rol]) VALUES (1, N'ADMINISTRADOR')
INSERT [dbo].[Roles] ([Id], [Rol]) VALUES (2, N'COMPRADOR')
SET IDENTITY_INSERT [dbo].[Roles] OFF
GO

# [dbo].[UsuarioLogin]

In [0]:
SET IDENTITY_INSERT [dbo].[UsuarioLogin] ON 
INSERT [dbo].[UsuarioLogin] ([Id], [EmailLogin], [Password], [CodigoRol]) VALUES (1, N'administrador@hotmail.com', N'12345', 1)
INSERT [dbo].[UsuarioLogin] ([Id], [EmailLogin], [Password], [CodigoRol]) VALUES (2, N'comprador@hotmail.com', N'1234567890', 2)
SET IDENTITY_INSERT [dbo].[UsuarioLogin] OFF
GO

# [dbo].[Venta]

In [0]:
SET IDENTITY_INSERT [dbo].[Venta] ON 
INSERT [dbo].[Venta] ([Id], [ClienteVenta], [FechaVenta], [SubtotalVenta], [IvaVenta], [TotalVenta]) VALUES (1, N'Fred Vizcaino', CAST(N'2022-05-11T00:00:00.000' AS DateTime), CAST(1620000.00 AS Decimal(11, 2)), CAST(380000.00 AS Decimal(11, 2)), CAST(2000000.00 AS Decimal(12, 2)))
INSERT [dbo].[Venta] ([Id], [ClienteVenta], [FechaVenta], [SubtotalVenta], [IvaVenta], [TotalVenta]) VALUES (2, N'Andres Vargas', CAST(N'2022-05-01T00:00:00.000' AS DateTime), CAST(2835000.00 AS Decimal(11, 2)), CAST(665000.00 AS Decimal(11, 2)), CAST(3500000.00 AS Decimal(12, 2)))
INSERT [dbo].[Venta] ([Id], [ClienteVenta], [FechaVenta], [SubtotalVenta], [IvaVenta], [TotalVenta]) VALUES (3, N'Carlos Diaz', CAST(N'2022-05-05T00:00:00.000' AS DateTime), CAST(16200000.00 AS Decimal(11, 2)), CAST(3800000.00 AS Decimal(11, 2)), CAST(20000000.00 AS Decimal(12, 2)))
SET IDENTITY_INSERT [dbo].[Venta] OFF
GO

# [FK_DetalleVenta_Producto]

In [0]:
ALTER TABLE [dbo].[DetalleVenta]  WITH CHECK ADD  CONSTRAINT [FK_DetalleVenta_Producto] FOREIGN KEY([CodigoProducto])
REFERENCES [dbo].[Producto] ([Id])
GO
ALTER TABLE [dbo].[DetalleVenta] CHECK CONSTRAINT [FK_DetalleVenta_Producto]
GO

# [FK_DetalleVenta_Venta]

In [0]:
ALTER TABLE [dbo].[DetalleVenta]  WITH CHECK ADD  CONSTRAINT [FK_DetalleVenta_Venta] FOREIGN KEY([CodigoVenta])
REFERENCES [dbo].[Venta] ([Id])
GO
ALTER TABLE [dbo].[DetalleVenta] CHECK CONSTRAINT [FK_DetalleVenta_Venta]
GO

# [FK_UsuarioLogin_Roles1]

In [0]:
ALTER TABLE [dbo].[UsuarioLogin]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioLogin_Roles1] FOREIGN KEY([CodigoRol])
REFERENCES [dbo].[Roles] ([Id])
GO
ALTER TABLE [dbo].[UsuarioLogin] CHECK CONSTRAINT [FK_UsuarioLogin_Roles1]
GO

# [dbo].[UsuarioBorrarProducto]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioBorrarProducto]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioBorrarProducto](
@idProducto int

)AS
BEGIN



 IF(SELECT count(*) FROM Producto where id= @idProducto)=0
 BEGIN 
		RAISERROR('Producto no encontrado',16,1);
		RETURN -1
 END

 IF(SELECT count(*) FROM DetalleVenta WHERE @idProducto=@idProducto)>0
  BEGIN 
		RAISERROR('Un Producto con Detalle de Venta no puede borrarse',16,1);
		RETURN -1
 END

-- Se eliminan las registros correspiondientes a las tablas Producto-DetalleVenta relacionadas
DELETE FROM dbo.DetalleVenta WHERE @idProducto=@idProducto

DELETE FROM Producto WHERE Id=@idProducto

END
GO

# [dbo].[UsuarioBuscarProductos]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioBuscarProductos]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioBuscarProductos](
@texto varchar(500)
)AS
BEGIN

SELECT * FROM dbo.Producto
where NombreProducto like '%'+@texto+'%' 



END
GO

# [dbo].[UsuarioBuscarProductosTopMasVendidos]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioBuscarProductosTopMasVendidos]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioBuscarProductosTopMasVendidos]

AS
BEGIN

SELECT TOP 3 P.NombreProducto 'PRODUCTO', MAX((DV.CantidadDetalleVenta)) 'PRODUCTOS MAS VENDIDOS', (SUM(V.TotalVenta)) VENTA
FROM Venta V INNER JOIN DetalleVenta DV ON V.Id = DV.Id 
             INNER JOIN Producto P ON p.Id = DV.Id  
GROUP  BY  P.NombreProducto, DV.CantidadDetalleVenta, V.TotalVenta
ORDER  BY V.TotalVenta DESC 



END
GO

# [dbo].[UsuarioBuscarProductosTopMenosVendidos]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioBuscarProductosTopMenosVendidos]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioBuscarProductosTopMenosVendidos]

AS
BEGIN

SELECT TOP 3 P.NombreProducto, MIN(DV.CantidadDetalleVenta) 'MENOS VENDIDOS', SUM(TotalVenta) VENTA
FROM Venta V INNER JOIN DetalleVenta DV ON V.Id = DV.Id 
             INNER JOIN Producto P ON p.Id = DV.Id
GROUP  BY P.NombreProducto, CantidadDetalleVenta, V.TotalVenta
ORDER  BY V.TotalVenta ASC;



END
GO

# [dbo].[UsuarioCrearDetalleVenta]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioCrearDetalleVenta]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--=============================================================================================
-- PROCEDIMIENTO ALMACENADO -> DETALLE VENTA
--=============================================================================================

CREATE PROCEDURE [dbo].[UsuarioCrearDetalleVenta](
@CodigoVenta int,
@CodigoProducto int,
@CantidadDetalleVenta int,
@PrecioVenta decimal(11,2),
@SubtotalDetalleVenta decimal(11,2)
)
AS
BEGIN

	INSERT INTO dbo.DetalleVenta(CodigoVenta,CodigoProducto,CantidadDetalleVenta,PrecioDetalleVenta,SubtotalDetalleVenta)
	VALUES (@CodigoVenta,@CodigoProducto,@CantidadDetalleVenta,@PrecioVenta,@SubtotalDetalleVenta)

END

GO

# [dbo].[UsuarioCrearProducto]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioCrearProducto]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--=============================================================================================
-- PROCEDIMIENTO ALMACENADO -> PRODUCTO
--=============================================================================================

CREATE PROCEDURE [dbo].[UsuarioCrearProducto](

@nombre varchar(100),
@descripcion varchar(100),
@precio decimal(11,2),
@imagen varchar(500),
@cantidad int
)AS
BEGIN

	INSERT INTO dbo.Producto(NombreProducto,DescripcionProducto,PrecioProducto,ImagenProducto,CantidadProducto) 
	VALUES(@nombre,@descripcion,@precio,@imagen,@cantidad)

END
GO

# [dbo].[UsuarioCrearVenta]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioCrearVenta]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--=============================================================================================
-- PROCEDIMIENTO ALMACENADO -> VENTA
--=============================================================================================

CREATE PROCEDURE [dbo].[UsuarioCrearVenta](
@Cliente int,
@CodigoProducto int,
@Cantidad int,
@PrecioVenta decimal(11,2),
@SubtotalDetalleVenta decimal(11,2)
)
AS
BEGIN

	INSERT INTO dbo.Venta(ClienteVenta,FechaVenta,SubtotalVenta,IvaVenta,TotalVenta)
	VALUES (@Cliente,Getdate(),@Cantidad,@PrecioVenta,@SubtotalDetalleVenta)

END

GO

# [dbo].[UsuarioDameDetalleVenta]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioDameDetalleVenta]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioDameDetalleVenta](
@id int =null

)AS
BEGIN

SELECT * FROM DetalleVenta WITH(NOLOCK) 
WHERE 
(@id IS NULL OR Id=@id) 



END
GO

# [dbo].[UsuarioDameProductos]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioDameProductos]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioDameProductos](
@id int =null,
@nombre varchar(500) =null
)AS
BEGIN

SELECT * FROM Producto WITH(NOLOCK) 
WHERE 
(@id IS NULL OR Id=@id) AND
(@nombre IS NULL OR NombreProducto=@nombre) 



END
GO

# [dbo].[UsuarioDameVenta]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioDameVenta]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioDameVenta](
@id int =null

)AS
BEGIN

SELECT * FROM Venta WITH(NOLOCK) 
WHERE 
(@id IS NULL OR Id=@id) 



END
GO

# [dbo].[UsuarioDameVentas]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioDameVentas]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioDameVentas](
@id int =null

)AS
BEGIN

SELECT * FROM Venta WITH(NOLOCK) 
WHERE 
(@id IS NULL OR Id=@id) 



END
GO

# [dbo].[UsuarioModificaProducto]

In [0]:
/****** Object:  StoredProcedure [dbo].[UsuarioModificaProducto]    Script Date: 15/05/2022 0:18:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UsuarioModificaProducto](
@Nombre varchar(500),
@Descripcion varchar(500),
@Precio decimal(11,2),
@Imagen varchar(500),
@Cantidad integer,
@FechaAlta datetime=null,
@IdProducto int =null

)AS
BEGIN

IF(@IdProducto IS NULL)
	BEGIN

		INSERT INTO dbo.Producto(NombreProducto,DescripcionProducto,PrecioProducto,ImagenProducto,CantidadProducto)
		VALUES(@Nombre,@Descripcion,@Precio,@Imagen,@Cantidad)

		SELECT @@IDENTITY as idProducto
	END
ELSE
BEGIN
	UPDATE dbo.Producto SET NombreProducto = @Nombre ,DescripcionProducto = @Descripcion,ImagenProducto = @Imagen,CantidadProducto = @Cantidad
	WHERE id=@IdProducto

	SELECT @IdProducto as idProducto
END


END
GO